### ISSUE TITLE
installについて

### ISSUE THREAD

**Issue by kngsmym** [inc2734/mimizuku-child#1]
私がよくわかってないだけだとは思いますが、installがタイムアウトしてしまいます。

[Symfony\Component\Process\Exception\ProcessTimedOutException]
The process "composer build-mimizuku" exceeded the timeout of 600 seconds. 

まず普通にインストールするとこのメッセージとともにタイムアウト

そこでmimizuku-childフォルダのcomposer.jsonのCOMPOSER_PROCESS_TIMEOUTを2000にして

$ composer build-mimizuku

とやってみましたが、

[Symfony\Component\Process\Exception\ProcessTimedOutException]
The process "current=$(cd $(dirname $0) && pwd) && cd ${current}/../mimizuku && composer install --no-dev && npm install && npm run gulp build" exceeded the timeout of 2000 seconds.

と出てタイムアウトします。

なにか根本的に間違ってますでしょうか。

**Comment by inc2734** [comment]
`composer install` の中で`npm install` も行うようにしているため、`npm install` に時間がかかると composer がタイムアウトしてしまうようなのです。
下記の手順を試してみてください。
1. `/mimizuku-child/vendor/` を削除
2. `/mimizuku/` も削除
3. `/mimizuku-child/composer.json` の `"process-timeout": 600` を `10000` とか大きい数字にする
4. もう一度 `composer install`

**Comment by kngsmym** [comment]
ご返答ありがとうございました。

何度か試してみたのですが、composer installで一括して実行するとタイムアウトしてしまうので、
composer.jsonのscriptsからpost-install-cmdを削除してその前まで一旦完了させて、その後build-mimizukuとbuild-mimizuku-childのコマンド群をそれぞれ個別に実行していったところ最後までたどり着きました。

回線速度が影響しているのかと思いますが、私の環境だとnpm installがそれぞれ20〜30分程度かかってしまうので、composer installに含めて一括して実行するのは難しいようです。

"process-timeout": 10000で実行したので理論的には数十分というのは許容範囲のはずですが、それでも実際にはタイムアウトしてしまってました。

以上ご報告です。
ご返答ありがとうございました。

**Comment by inc2734** [comment]
むーんなるほどです。テスト頂いてありがとうございます。そういうことであれば`npm install`を`composer`の中でやるということ自体見直したほうが良さそうですね。

**Comment by kngsmym** [comment]
調整ありがとうございました。
本件こちらで解決いたしました。
