### ISSUE TITLE
インストールについてnpm ERR! Error: ENOENT, open ～ /gulp/package.json

### ISSUE THREAD

**Issue by phssakaigawa** [inc2734/mimizuku-child#2]
habakiriいつも大事に使わせていただいています。

mimizukuの魅力に惹かれ、blog記事からボクも試して見ようとチャレンジしています。
http://2inc.org/blog/2016/12/13/5509/

勉強不足で申し訳ありません、質問させてください。
git clone後、composer installを行ったのですが、以下エラーとなります。

`> npm run gulp build
npm ERR! Error: ENOENT, open '/var/www/html/wp-content/themes/you/node_modules/gulp/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-642.11.1.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "run" "gulp" "build"
npm ERR! cwd /var/www/html/wp-content/themes/you
npm ERR! node -v v0.10.46
npm ERR! npm -v 1.3.6
npm ERR! path /var/www/html/wp-content/themes/you/node_modules/gulp/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/html/wp-content/themes/you/npm-debug.log
npm ERR! not ok code 0
Script npm run gulp build handling the post-update-cmd event returned with error code 34
`

前のIssueで回答されている、venderの削除、mimizukuの削除後に、composer installをリトライかけることで、
composer install 自体は通るのですが、wp theme activate が
「Error: スタイルシートが見つかりません。」
通らない状況です。

composer install後、cssのビルドなど手順が必要なのでしょうか。

**Comment by inc2734** [comment]
もしかしたらお使いの環境の npm （か Node）のバージョンが低いのかもしれません。
僕の場合だと、
```
$ npm -v
3.7.3
$ node -v
v5.8.0
```
なのですが、お使いの環境のバージョンはいくつでしょうか？

**Comment by phssakaigawa** [comment]
ありがとうございます。

圧倒的なふるさに自分もびっくりしました

CentOS6.8にepelでnodejsをyum installして環境を作っていました。
nodejs自体の導入を見直してみます

```
$ npm -v
1.3.6
$ node -v                                                                                                  
v0.10.46
```

**Comment by phssakaigawa** [comment]
続報です。
http://qiita.com/ozawan/items/86ca7551d59005128892
のnvmでインストールする場合を参考に、最新版stableのnodejs/npmをインストールしました。

/mimizuku-child/vendor/ と/mimizuku/ を削除して、composer installしなおすと
style.cssまでビルドされてきました。

```
$ npm -v
3.10.10
$ node -v
v7.2.1
```
ありがとうございます！！

**Comment by inc2734** [comment]
バージョンだったですね。解決したとのことで良かったです！issue 閉じますね。
